language: c
dist: xenial

env:
  global:
    - DB=mysql OSSEC_TYPE=server GEOIP=yes ZEROMQ=yes
    - secure: "Hyq0J4XSx5dm1WxYXBFcicM1EG4jYHkcyQRK/UlADPgN48kvC6s14maznlRfoqXnnbkDFsGKEj50HX2Al98m/tXME8zDJNVcxr4ZCo8FnhvsXQFHivJmM5m6fwEEH4s4sTYi1tpbd1bq7DUdmxwYuHOdRK9s8EqnhuZ8bCVz+ts="

addons:
  coverity_scan:
    project:
      name: "ossec/ossec-hids"
      description: "OSSEC is an Open Source Host Intrusion Detection System"
    notification_email: ddpbsd@gmail.com
    build_command_prepend: "cd src"
    build_command:   "make TARGET=server"
    branch_pattern: coverity_scan

compiler:
- gcc


matrix:
  fast_finish: true

before_script:
- sudo apt-get update -qq
- sudo apt-get install -y libevent-dev automake autoconf m4 perl libtool
- cd src/external/pcre2-10.32 && autoreconf -f -i && cd ../../..
- if [[ "${GEOIP}" == "yes"  ]]; then ( sudo apt-get install geoip-bin geoip-database libgeoip-dev libgeoip1 ); fi
- if [[ "${PRELUDE}" == "yes" ]]; then ( sudo apt-get install libprelude-dev ); fi
- if [[ "${ZEROMQ}" == "yes" ]]; then ( sudo apt-get install libzmq3-dev libtool autoconf libczmq-dev ); fi
- if [[ "${OSSEC_TYPE}" == "winagent" ]]; then ( sudo apt-get install aptitude && sudo aptitude -y install mingw-w64 nsis ); fi
- if [[ "${OSSEC_TYPE}" == "server" ]]; then ( sudo apt-get install libsqlite3-dev sqlite3 ); fi
- if [[ "${OSSEC_TYPE}" == "test" ]]; then ( sudo apt-get update && sudo apt-get install check valgrind ); fi


script:
- COMMAND="V=1 TARGET=${OSSEC_TYPE} PCRE2_SYSTEM=no"
  && if ! [[ "${DB}" = "none" ]]; then COMMAND="${COMMAND} DATABASE=${DB}"; fi
  && if [[ "${GEOIP}" = "yes" ]]; then COMMAND="${COMMAND} USE_GEOIP=1"; fi
  && if [[ "${PRELUDE}" = "yes" ]]; then COMMAND="${COMMAND} USE_PRELUDE=1"; fi
  && if [[ "${ZEROMQ}" = "yes" ]]; then COMMAND="${COMMAND} USE_ZEROMQ=1"; fi
  && if [[ "${OSSEC_TYPE}" = "test" ]]; then COMMAND="${COMMAND} USE_PCRE2_JIT=0"; fi
  && ( cd src/
     && make --warn-undefined-variables ${COMMAND} settings
     && make --warn-undefined-variables ${COMMAND} external -j
     && make --warn-undefined-variables ${COMMAND} -j )
  && if ! [[ "${OSSEC_TYPE}" = "test" || "${OSSEC_TYPE}" = "winagent" ]]; then ( cd src/ && sudo make --warn-undefined-variables ${COMMAND} install ) fi

- if [[ "${OSSEC_TYPE}" == "test" ]]; then ( cd src/ && make --warn-undefined-variables test_valgrind ) fi
- if [[ "${RULES}" == "test" ]]; then ( cd src/ && sudo make V=1 TARGET=server test-rules ) fi


deploy:
  provider: releases
  api_key:
    secure: "DiVPTCt1C8XCmFlzcpmFkqfRmxz85/RCE2euvU/c1EiABjfO20aZARCC9zsepAwAGWWsq3uGRLp0aVuJuh4LvTdGxIJDOqYR8z1pByfY4epgE7zmRCIWjx+nAwBpLlfYalMWFpt7vmPp9mKycFkUR2NFoiEfOgoO9wGN0ZgmwSM="
  file: src/win-pkg/ossec-win32-agent.exe
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: ossec/ossec-hids
    condition: $OSSEC_TYPE = winagent

